### ISSUE TITLE
Sample app: func pressed(sender: UIButton!) isn't called

### ISSUE THREAD

**Issue by apparition47** [apparition47/BreadCrumbControl#12]
@rikusouda In the sample app, `func pressed(sender: UIButton!) {}` isn't called.

Steps to reproduce (iPhone 7 Plus simulator)

1. tap on "Config > Alarm > Detector > Kitchen > ...(very long)
2. tap on "Very tasty ale beer" on the `BreadCrumbControl`, nothing happens
3. scroll `BreadCrumbControl` left, tap on "Detector" (UIAlert pops up as expected)

**Comment by rikusouda** [comment]
On iPad Air 2, this issue not reproduce. The cause of the bug may be that the button is out of bounds of superView

**Comment by rikusouda** [comment]
Because "Very tasty ale beer" button is out of bounds of `containerView`, Button is not handle touch event.

**Comment by apparition47** [comment]
Ah, it's a bug with the sample app. I think that's why the original author set it to iPad-only before, so he wouldn't have to layout the view for small devices.

**Comment by rikusouda** [comment]
In case of scrolling is needed, this issue is reproduce on our product application. So, I think we'd like to fix it.

**Comment by rikusouda** [comment]
#11 is too big change. I want to fix it after #11 is merged. (It's no problem even if you can not merge immediately)

**Comment by apparition47** [comment]
Thanks again!
