### ISSUE TITLE
AutoScroll position is wrong when item is empty

### ISSUE THREAD

**Issue by rikusouda** [apparition47/BreadCrumbControl#17]
![breadcrumb_scroll_bug](https://user-images.githubusercontent.com/25785565/30040790-bf1015f4-921e-11e7-8f16-d0f7049180cb.gif)
When `Config` button added again, position is not left end.

Reproduce steps
1. Start sample app
2. Tap `Config > Output > Relay`
3. Tap `Clear`
4. Tap `Config > Output > Relay` again

**Comment by rikusouda** [comment]
Calculating offset was wrong.

**Comment by apparition47** [comment]
From your reproduction steps. Looks you fixed this issue.


One very small I noticed when the BreadCrumb list is long then you shrink it is that it doesn't scroll backward (or forward) as items are added to the list. It scrolls after items are added and animation is complete. 

(sample app, iPhone 7 Plus, tag `0.0.5`)
1. tap on "...(very long)"
2. tap on "Config"
![sep-13-2017 01-45-37](https://user-images.githubusercontent.com/3298414/30338080-52156b4a-9825-11e7-8e78-9fd4df220dc5.gif)

Maybe it could scroll as items are added/removed instead?

**Comment by rikusouda** [comment]
I agree your idea. That's not good. It's good to scroll at the right time.

**Comment by apparition47** [comment]
Resolved from PR #20. Love it.

**Comment by rikusouda** [comment]
Thanks for confirm😋
