### ISSUE TITLE
Cannot disabled last arrow, when `style` is `defaultFlatStyle`

### ISSUE THREAD

**Issue by rikusouda** [apparition47/BreadCrumbControl#7]
When `CBreadcrumbControl.style` is `defaultFlatStyle`, last arrow is sometimes unnecessary.
<img width="340" alt="last_arrow" src="https://user-images.githubusercontent.com/25785565/29757672-873e9bbe-8be8-11e7-8e76-9667479501dc.png">

So I want to make disabled it, in `defaultFlatStyle` case.

**Comment by apparition47** [comment]
Appreciate the PR!
