### ISSUE TITLE
Crash if it set `CBreadcrumbControl#itemsBreadCrumb` during animation

### ISSUE THREAD

**Issue by rikusouda** [apparition47/BreadCrumbControl#9]
Reproduce steps:
1. Start sample app
2. Set `Animation`(speed) to large value (Ex. 1.0)
3. Touch `Config > Output > Relay`
4. Touch `Config` during animation

**Comment by rikusouda** [comment]
Using `itemsBCInWaiting` it is trying to do things like queuing. But it doesn't work completely. `initialSetup` is called from `didSet` of `itemsBreadCrumb` and `layoutSubviews`. I think that consideration for them is missing. For example `_items` are broken by `layoutSubviews` after it set `itemsBreadCrumb`.

**Comment by apparition47** [comment]
I used this module in a [small side project](https://itunes.apple.com/ca/app/synnamon-word-cloud-thesaurus/id1156731332?mt=8) and I noticed crashes as well so I was using a **bad** workaround that fixed my crashes:

```swift
class ViewController: UIViewController {
	@IBOutlet weak var breadcrumbView: CBreadcrumbControl!
	func addToBreadCrumbView(with word: String) {
	    DispatchQueue.main.async {
	            self.breadcrumbView.itemsBreadCrumb += [word]
	        }
	    }
	}
}
```

You **shouldn't** be doing this though. The queuing needs refactoring for sure.

**Comment by rikusouda** [comment]
Thanks for workaround. But it doesn't work in my project.

**Comment by rikusouda** [comment]
I remove `initialSetup` calling on `layoutSubView`. So, this issue no longer reproduce. But completely queueing is not implemented.

**Comment by rikusouda** [comment]
I implemented queueing

**Comment by apparition47** [comment]
Are you able to reproduce crashes anymore with `/fix_toomany_create_button`?

**Comment by rikusouda** [comment]
> Are you able to reproduce crashes anymore with `/fix_toomany_create_button`?

I have not crashed in my confirmed. If we see crash, register new issue.

**Comment by apparition47** [comment]
Works from what I can see! Thanks again!
